import { useState } from 'react'
import {
  Building2,
  CalendarClock,
  FileCheck2,
  OctagonAlert,
  Package,
  PlaneTakeoff,
  ScrollText,
  Timer,
  TriangleAlert,
  Users,
  Wrench,
} from 'lucide-react'
import { accounts, availabilityTrend } from '@/data'
import { fmtDateTime } from '@/lib/format'
import { PageHeader } from '@/components/shell/PageHeader'
import { DataTable, type Column } from '@/components/ui/DataTable'
import { FilterBar, SelectFilter } from '@/components/ui/FilterBar'
import { HBarChart, Sparkline } from '@/components/ui/Charts'

interface RecentReport {
  id: string
  name: string
  filters: string
  generatedBy: string
  generatedAt: string
  period: string
  format: string
}

const RECENT_REPORTS: RecentReport[] = [
  {
    id: 'RPT-1',
    name: 'Fleet availability',
    filters: 'All types · MEL & MQL',
    generatedBy: 'R. Torres',
    generatedAt: '2026-07-15T09:15',
    period: 'Last 7 days',
    format: 'CSV',
  },
  {
    id: 'RPT-2',
    name: 'Audit activity',
    filters: 'All modules · This month',
    generatedBy: 'L. Andersson',
    generatedAt: '2026-07-15T07:40',
    period: 'This month',
    format: 'CSV',
  },
  {
    id: 'RPT-3',
    name: 'Work-order ageing',
    filters: 'Open statuses only',
    generatedBy: 'P. Raman',
    generatedAt: '2026-07-14T16:05',
    period: 'This week',
    format: 'PDF',
  },
  {
    id: 'RPT-4',
    name: 'Account costs',
    filters: 'All accounts · MTD',
    generatedBy: 'R. Torres',
    generatedAt: '2026-07-14T11:22',
    period: 'This month',
    format: 'CSV',
  },
  {
    id: 'RPT-5',
    name: 'Sign-off history',
    filters: 'Licensed engineers · Last 90 days',
    generatedBy: 'L. Andersson',
    generatedAt: '2026-07-13T14:50',
    period: 'Last 90 days',
    format: 'PDF',
  },
]

const columns: Column<RecentReport>[] = [
  {
    key: 'name',
    header: 'Report',
    render: (r) => (
      <>
        <span className="cell-main">{r.name}</span>
        <span className="cell-sub">{r.filters}</span>
      </>
    ),
  },
  { key: 'by', header: 'Generated by', render: (r) => r.generatedBy },
  { key: 'at', header: 'Generated', render: (r) => <span className="nowrap">{fmtDateTime(r.generatedAt)}</span> },
  { key: 'period', header: 'Period', render: (r) => r.period },
  { key: 'format', header: 'Format', render: (r) => <span className="chip">{r.format}</span> },
  {
    key: 'action',
    header: '',
    render: () => (
      <button type="button" className="btn btn--ghost btn--sm">
        Download
      </button>
    ),
  },
]

export function ReportsPage() {
  const [period, setPeriod] = useState('')
  const [acType, setAcType] = useState('')
  const [base, setBase] = useState('')

  const availabilityValues = availabilityTrend.map((d) => d.available)
  const accountCostRows = accounts.map((a) => ({
    label: a.code,
    value: Math.round(a.currentCostMtd / 1000),
    tone: 'accent' as const,
  }))

  return (
    <div className="page">
      <PageHeader
        crumbs={[{ label: 'Reports' }]}
        title="Reports"
        description="Operational and commercial reporting drawn from live fleet, maintenance and inventory data. Every export below is a visual preview."
        actions={
          <button type="button" className="btn btn--secondary">
            <CalendarClock size={15} aria-hidden="true" />
            Schedule report
          </button>
        }
      />

      <section className="card">
        <div className="card-header">
          <FilterBar>
            <SelectFilter
              label="Period"
              allLabel="This month"
              options={['This week', 'This month', 'Last 30 days', 'Custom range…']}
              value={period}
              onChange={setPeriod}
            />
            <SelectFilter
              label="Aircraft type"
              allLabel="All types"
              options={['ATR 72-600', 'DHC-8-315', 'Saab 340B', 'King Air 350']}
              value={acType}
              onChange={setAcType}
            />
            <SelectFilter label="Base" allLabel="All bases" options={['MEL', 'MQL']} value={base} onChange={setBase} />
            <button type="button" className="btn btn--secondary">
              Apply filters
            </button>
          </FilterBar>
        </div>
      </section>

      <div className="report-grid">
        <article className="report-card">
          <span className="report-icon">
            <PlaneTakeoff size={17} aria-hidden="true" />
          </span>
          <h3>Fleet availability</h3>
          <p>Daily available, maintenance and AOG counts across the network for the selected period.</p>
          <Sparkline values={availabilityValues} ariaLabel="Fleet availability trend, past 7 days" tone="green" />
          <div className="report-foot">
            <button type="button" className="btn btn--secondary btn--sm">
              Run report
            </button>
            <button type="button" className="btn btn--ghost btn--sm">
              Export CSV
            </button>
          </div>
        </article>

        <article className="report-card">
          <span className="report-icon">
            <OctagonAlert size={17} aria-hidden="true" />
          </span>
          <h3>AOG duration</h3>
          <p>Time on ground for grounding events this month — 1 event, VH-RXT still recovering at MQL.</p>
          <HBarChart ariaLabel="AOG duration this month" unit="h" rows={[{ label: 'VH-RXT', value: 5.3, tone: 'red', detail: 'ongoing' }]} />
          <div className="report-foot">
            <button type="button" className="btn btn--secondary btn--sm">
              Run report
            </button>
            <button type="button" className="btn btn--ghost btn--sm">
              Export CSV
            </button>
          </div>
        </article>

        <article className="report-card">
          <span className="report-icon">
            <TriangleAlert size={17} aria-hidden="true" />
          </span>
          <h3>Defect trends</h3>
          <p>Weekly reported-defect counts, split by severity, over the trailing seven weeks.</p>
          <Sparkline values={[2, 1, 3, 2, 4, 3, 5]} ariaLabel="Weekly defect counts, past 7 weeks" tone="orange" />
          <div className="report-foot">
            <button type="button" className="btn btn--secondary btn--sm">
              Run report
            </button>
            <button type="button" className="btn btn--ghost btn--sm">
              Export CSV
            </button>
          </div>
        </article>

        <article className="report-card">
          <span className="report-icon">
            <Wrench size={17} aria-hidden="true" />
          </span>
          <h3>Work-order ageing</h3>
          <p>Open work orders bucketed by time since creation — highlights anything stuck past a week.</p>
          <HBarChart
            ariaLabel="Work orders by age bucket"
            rows={[
              { label: '<24h', value: 3, tone: 'accent' },
              { label: '1–3d', value: 4, tone: 'accent' },
              { label: '3–7d', value: 1, tone: 'accent' },
              { label: '>7d', value: 1, tone: 'orange' },
            ]}
          />
          <div className="report-foot">
            <button type="button" className="btn btn--secondary btn--sm">
              Run report
            </button>
            <button type="button" className="btn btn--ghost btn--sm">
              Export CSV
            </button>
          </div>
        </article>

        <article className="report-card">
          <span className="report-icon">
            <Users size={17} aria-hidden="true" />
          </span>
          <h3>Engineer workload</h3>
          <p>Recorded labour hours by engineer this week, for capacity and roster planning.</p>
          <HBarChart
            ariaLabel="Engineer workload this week, hours"
            unit="h"
            rows={[
              { label: 'J. Munro', value: 6, tone: 'accent' },
              { label: 'S. Grech', value: 3, tone: 'accent' },
              { label: 'D. Reyes', value: 2, tone: 'accent' },
            ]}
          />
          <div className="report-foot">
            <button type="button" className="btn btn--secondary btn--sm">
              Run report
            </button>
            <button type="button" className="btn btn--ghost btn--sm">
              Export CSV
            </button>
          </div>
        </article>

        <article className="report-card">
          <span className="report-icon">
            <Timer size={17} aria-hidden="true" />
          </span>
          <h3>Maintenance turnaround</h3>
          <p>Actual versus estimated manhours on closed work orders, tracked across recent packages.</p>
          <Sparkline values={[3.2, 2.8, 4.1, 3.6, 2.4, 3.9, 3.1]} ariaLabel="Maintenance turnaround trend, hours" tone="blue" />
          <div className="report-foot">
            <button type="button" className="btn btn--secondary btn--sm">
              Run report
            </button>
            <button type="button" className="btn btn--ghost btn--sm">
              Export CSV
            </button>
          </div>
        </article>

        <article className="report-card">
          <span className="report-icon">
            <FileCheck2 size={17} aria-hidden="true" />
          </span>
          <h3>Sign-off history</h3>
          <p>Releases to service by day, split by line release, return-to-service and inspection sign-offs.</p>
          <Sparkline values={[1, 0, 1, 1, 2, 1, 2]} ariaLabel="Sign-offs per day, past 7 days" tone="green" />
          <div className="report-foot">
            <button type="button" className="btn btn--secondary btn--sm">
              Run report
            </button>
            <button type="button" className="btn btn--ghost btn--sm">
              Export CSV
            </button>
          </div>
        </article>

        <article className="report-card">
          <span className="report-icon">
            <Package size={17} aria-hidden="true" />
          </span>
          <h3>Inventory usage</h3>
          <p>Parts consumption by category this month — highlights the categories driving stores activity.</p>
          <HBarChart
            ariaLabel="Inventory usage by category this month"
            rows={[
              { label: 'Lighting', value: 3, tone: 'accent' },
              { label: 'Hydraulics', value: 2, tone: 'accent' },
              { label: 'Interiors', value: 2, tone: 'accent' },
            ]}
          />
          <div className="report-foot">
            <button type="button" className="btn btn--secondary btn--sm">
              Run report
            </button>
            <button type="button" className="btn btn--ghost btn--sm">
              Export CSV
            </button>
          </div>
        </article>

        <article className="report-card">
          <span className="report-icon">
            <Building2 size={17} aria-hidden="true" />
          </span>
          <h3>Account costs</h3>
          <p>Month-to-date maintenance spend by account, in thousands, for commercial review.</p>
          <HBarChart ariaLabel="Account costs month-to-date, thousands of dollars" unit="k" rows={accountCostRows} />
          <div className="report-foot">
            <button type="button" className="btn btn--secondary btn--sm">
              Run report
            </button>
            <button type="button" className="btn btn--ghost btn--sm">
              Export CSV
            </button>
          </div>
        </article>

        <article className="report-card">
          <span className="report-icon">
            <ScrollText size={17} aria-hidden="true" />
          </span>
          <h3>Audit activity</h3>
          <p>System-wide audit log volume by day — useful for spotting unusual activity spikes.</p>
          <Sparkline values={[3, 4, 2, 6, 5, 8, 7]} ariaLabel="Audit log entries per day, past 7 days" tone="grey" />
          <div className="report-foot">
            <button type="button" className="btn btn--secondary btn--sm">
              Run report
            </button>
            <button type="button" className="btn btn--ghost btn--sm">
              Export CSV
            </button>
          </div>
        </article>
      </div>

      <section className="card">
        <div className="card-header">
          <h2 className="card-title">Recent reports</h2>
        </div>
        <DataTable caption="Recently generated reports" columns={columns} rows={RECENT_REPORTS} rowKey={(r) => r.id} />
        <div className="card-footer">Exports are visual only in this preview — no files are generated or downloaded.</div>
      </section>
    </div>
  )
}
